version: '2'
services:
  php:
    image: yiisoftware/yii2-php:8.3-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    environment:
      - PHP_USER_ID=1000
    ports:
      - '8000:80'
  mysql:
    image: mysql:5.7
    container_name: yii2basic_mysql
    restart: on-failure:5
    ports:
      - "33060:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=yii2basic
      - MYSQL_USER=yii2basic
      - MYSQL_PASSWORD=secret
